# frozen_string_literal: true

# This class is responsible for refreshing the
# library_staff_document table from the csv
# file generated by lib-jobs
class LibraryStaffLoadingService < CSVLoadingService
  private

  def class_to_load
    LibraryStaffRecord
  end

  def expected_headers
    %w[puid netid phone name lastName firstName email address building department division
       unit team title areasOfStudy websiteUrl bios expertise mySchedulerLink otherEntities]
  end

  def uri
    @uri ||= URI.parse('https://lib-jobs.princeton.edu/pul-staff-report.csv')
  end
end
