# frozen_string_literal: true

# This class is responsible for refreshing the
# library_staff_document table from the csv
# file generated by lib-jobs
class LibraryStaffLoadingService < CSVLoadingService
  private

  def process_data
    repository.delete
    repository.new_from_csv remove_empty_rows(csv)
  end

  def existing_records
    repository.library_staff_records.count
  end

  def remove_empty_rows(rows)
    rows.filter { |row| !row.all? { |cell| cell.nil? || cell.strip.empty? } }
  end

  def expected_headers
    %w[puid netid phone name lastName firstName email address building department division
       unit team title areasOfStudy websiteUrl bios expertise mySchedulerLink otherEntities]
  end

  def uri
    @uri ||= URI.parse('https://lib-jobs.princeton.edu/pul-staff-report.csv')
  end

  def repository
    @repository ||= LibraryStaffRepository.new(Rails.application.config.rom)
  end
end
