inherit_from: .rubocop_todo.yml
plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'solr/**/*'
    - 'tmp/**/*'
    - 'vendor/bundle/**/*'

Layout/LineLength:
  Exclude:
    - 'spec/relations/best_bet_relation_spec.rb'

Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'lib/tasks/**/*'

Naming/RescuedExceptionsVariableName:
  PreferredName: error

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/requests/api/*'

RSpec/NestedGroups:
  Exclude:
    - 'spec/relations/best_bet_relation_spec.rb'

RSpec/RepeatedDescription:
  Exclude:
    - 'spec/requests/api/*'

RSpec/RepeatedExample:
  Exclude:
    - 'spec/requests/api/*'

RSpec/SpecFilePathFormat:
  Exclude:
    - 'spec/models/oauth_token_cache_spec.rb'
    - 'spec/services/oauth_service_spec.rb'

Style/BitwisePredicate:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SafeNavigationChainLength:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets
  MinSize: 8
